// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { getDatabase, ref, child, get, onValue } from "firebase/database";

import Head from 'next/head'
import Image from 'next/image'


// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyBWJqnM4LQOaMwM5w5bAz95ZjW7tGhyeDk",
  authDomain: "iscf-lab1-1b00a.firebaseapp.com",
  databaseURL: "https://iscf-lab1-1b00a-default-rtdb.europe-west1.firebasedatabase.app",
  projectId: "iscf-lab1-1b00a",
  storageBucket: "iscf-lab1-1b00a.appspot.com",
  messagingSenderId: "720639757067",
  appId: "1:720639757067:web:b4ab9f49f6b046acaab00e",
  measurementId: "G-CVYF8W8KMY"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
//const analytics = getAnalytics(app);


const db = getDatabase(app);

let timestampValues = [];
let xValues = [];
let yValues = [];
let zValues = [];

//export {db};

const dbRef = ref(db, '/accel/');

var i = Number(0);





onValue(dbRef, (snapshot) => {
  snapshot.forEach((childSnapshot) => {
    const childKey = childSnapshot.key; // nome da variavel
    const dbRefUtil = ref(db, '/accel/' + childKey); // path + variavel depois accel
    
    const childData = childSnapshot.val(); // valor em si
    get(child(dbRefUtil, 'timestamp')).then((snapshot) => { // Trocar para variavel desejada
      if (snapshot.exists()) {
        
        timestampValues[i] = snapshot.val();
        // console.log(timestampValues[i]);
        //i++;
      } else {
        console.log("No data available");
      }
    }).catch((error) => {
      console.error(error);
    });
    get(child(dbRefUtil, 'x')).then((snapshot) => { // Trocar para variavel desejada
      if (snapshot.exists()) {
        
        xValues[i] = snapshot.val();
        // console.log(xValues[i]);
        //i++;
      } else {
        console.log("No data available");
      }
    }).catch((error) => {
      console.error(error);
    });
    get(child(dbRefUtil, 'y')).then((snapshot) => { // Trocar para variavel desejada
      if (snapshot.exists()) {
        
        yValues[i] = snapshot.val();
        // console.log(yValues[i]);
        //i++;
      } else {
        console.log("No data available");
      }
    }).catch((error) => {
      console.error(error);
    });
    get(child(dbRefUtil, 'z')).then((snapshot) => { // Trocar para variavel desejada
      if (snapshot.exists()) {
        
        zValues[i] = snapshot.val();
        // console.log(zValues[i]);
        //i++;
      } else {
        console.log("No data available");
      }
      i++;
    }).catch((error) => {
      console.error(error);
    });
    
    // ...
  });
}, {
  onlyOnce: true
});


export {timestampValues, xValues, yValues, zValues};

export default function Home() {
  return (
    <>
      <Head>
        <title>Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        
      </main>
    </>
  )
}

